mo/config/routes.rb
Mo::Application.routes.draw do
  resources :moshikomis ,:except =>['index']  do
    collection  do 
      get 'start'
      get 'search'
    end
  end
  match 'moshikomis' => 'moshikomis#start', :via =>:get,:as =>'moshikomi'
  root :to => "moshikomis#start"
end

mo/app/models/moshikomi.rb
class Moshikomi < ActiveRecord::Base
end

mo/app/models/search.rb
class Search < ActiveRecord::Base
end

mo/app/models/search_qaery.rb
require 'active_model'

class SearchQaery 
  include ActiveModel::Validations
  include ActiveModel::Conversion
  def persisted?
     false
  end

  validates_presence_of :start_date,:end_date

  attr_accessor :start_date,:end_date,:comment,:title

# how  can I get paramete date ??
# TODO

#  def initialize(params = nil)
#    return unless params
#    p params
#    p "hoge"
#    p params[:comment]
#    self.start_date = params[:start_date]
#    self.end_date = params[:end_date]
##    self.comment = params[:comment]
#    p "hoge"
#  end

  def print()
    str = start_date.to_s + " " + end_date.to_s + " " + comment.to_s
  end
end

mo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

mo/app/controllers/moshikomis_controller.rb
class MoshikomisController < ApplicationController
  # GET /moshikomis
  # GET /moshikomis.xml

  def start
  end

  def search
    @searchQaery = SearchQaery.new(params[:search_qaery])
    str = @searchQaery.print
    p str
    @moshikomis = Moshikomi.all
  end

  # GET /moshikomis/1
  # GET /moshikomis/1.xml
  def show
    @moshikomi = Moshikomi.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @moshikomi }
    end
  end

  # GET /moshikomis/new
  # GET /moshikomis/new.xml
  def new
    @moshikomi = Moshikomi.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @moshikomi }
    end
  end

  # GET /moshikomis/1/edit
  def edit
    @moshikomi = Moshikomi.find(params[:id])
  end

  # POST /moshikomis
  # POST /moshikomis.xml
  def create
    @moshikomi = Moshikomi.new(params[:moshikomi])

    respond_to do |format|
      if @moshikomi.save
        format.html { redirect_to(@moshikomi, :notice => 'Moshikomi was successfully created.') }
        format.xml  { render :xml => @moshikomi, :status => :created, :location => @moshikomi }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @moshikomi.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /moshikomis/1
  # PUT /moshikomis/1.xml
  def update
    @moshikomi = Moshikomi.find(params[:id])

    respond_to do |format|
      if @moshikomi.update_attributes(params[:moshikomi])
        format.html { redirect_to(@moshikomi, :notice => 'Moshikomi was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @moshikomi.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /moshikomis/1
  # DELETE /moshikomis/1.xml
  def destroy
    @moshikomi = Moshikomi.find(params[:id])
    @moshikomi.destroy

    respond_to do |format|
      format.html { redirect_to(moshikomis_url) }
      format.xml  { head :ok }
    end
  end
end

mo/app/helpers/application_helper.rb
module ApplicationHelper
end

mo/app/helpers/moshikomis_helper.rb
module MoshikomisHelper
end

mo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mo</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

mo/app/views/moshikomis/_form.html.erb
<%= form_for(@moshikomi) do |f| %>
  <% if @moshikomi.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@moshikomi.errors.count, "error") %> prohibited this moshikomi from being saved:</h2>

      <ul>
      <% @moshikomi.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :hyouka_kubun %><br />
    <%= f.text_field :hyouka_kubun %>
  </div>
  <div class="field">
    <%= f.label :koshinyotei_date %><br />
    <%= f.date_select :koshinyotei_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

mo/app/views/moshikomis/edit.html.erb
<h1>Editing moshikomi</h1>

<%= render 'form' %>

<%= link_to 'Show', @moshikomi %> |
<%= link_to 'Back', moshikomis_path %>

mo/app/views/moshikomis/index.html.erb
<h1>Listing moshikomis</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Comment</th>
    <th>Hyouka kubun</th>
    <th>Koshinyotei date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @moshikomis.each do |moshikomi| %>
  <tr>
    <td><%= moshikomi.title %></td>
    <td><%= moshikomi.comment %></td>
    <td><%= moshikomi.hyouka_kubun %></td>
    <td><%= moshikomi.koshinyotei_date %></td>
    <td><%= link_to 'Show', moshikomi %></td>
    <td><%= link_to 'Edit', edit_moshikomi_path(moshikomi) %></td>
    <td><%= link_to 'Destroy', moshikomi, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Moshikomi', new_moshikomi_path %>

mo/app/views/moshikomis/new.html.erb
<h1>New moshikomi</h1>

<%= render 'form' %>

<%= link_to 'Back', moshikomi_path %>

mo/app/views/moshikomis/search.html.erb
<h1>search adn Listing moshikomis</h1>

<% form_for @searchQaery, 
         :url=> {:action=>'search',:controller =>'moshikomis'},
         :html =>{:method => :get}   do |f| %>

  <% if @searchQaery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@searchQaery.errors.count, "error") %> 
      prohibited this search qaery from being searched:</h2>

      <ul>
      <% @searchQaery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<table>
  <tr>
    <th>Title</th>
    <th>Comment</th>
    <th>Hyouka kubun</th>
    <th>Koshinyotei date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @moshikomis.each do |moshikomi| %>
  <tr>
    <td><%= moshikomi.title %></td>
    <td><%= moshikomi.comment %></td>
    <td><%= moshikomi.hyouka_kubun %></td>
    <td><%= moshikomi.koshinyotei_date %></td>
    <td><%= link_to 'Show', moshikomi %></td>
    <td><%= link_to 'Edit', edit_moshikomi_path(moshikomi) %></td>
    <td><%= link_to 'Destroy', moshikomi, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Moshikomi', new_moshikomi_path %>
<%= link_to 'Back', moshikomi_path %>

mo/app/views/moshikomis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @moshikomi.title %>
</p>

<p>
  <b>Comment:</b>
  <%= @moshikomi.comment %>
</p>

<p>
  <b>Hyouka kubun:</b>
  <%= @moshikomi.hyouka_kubun %>
</p>

<p>
  <b>Koshinyotei date:</b>
  <%= @moshikomi.koshinyotei_date %>
</p>


<%= link_to 'Edit', edit_moshikomi_path(@moshikomi) %> |
<%= link_to 'Back', moshikomis_path %>

mo/app/views/moshikomis/start.html.erb
<h1>Start MOshikomi</h1>

<table>
  <tr>
    <th>New</th>
    <td><%= link_to 'New', new_moshikomi_path %></td>
  </tr>
  <tr>
    <th>Search</th>
    <td><%= link_to 'Search', search_moshikomis_path %></td>
  </tr>
</table>